//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handbrake_Batch_Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Handbrake_Batch_Creator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindinFiles_16x {
            get {
                object obj = ResourceManager.GetObject("FindinFiles_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap handbrake_logo {
            get {
                object obj = ResourceManager.GetObject("handbrake_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ArrayOfQueueTask&gt;.
        /// </summary>
        internal static string HBQFooter {
            get {
                return ResourceManager.GetString("HBQFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;ArrayOfQueueTask xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;.
        /// </summary>
        internal static string HBQHeader {
            get {
                return ResourceManager.GetString("HBQHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QueueTask&gt;
        ///  &lt;ScannedSourcePath&gt;{$source}&lt;/ScannedSourcePath&gt;
        ///  &lt;Status&gt;Waiting&lt;/Status&gt;
        ///  &lt;Task&gt;
        ///    &lt;Source&gt;{$source}&lt;/Source&gt;
        ///    &lt;Title&gt;1&lt;/Title&gt;
        ///    &lt;Angle&gt;1&lt;/Angle&gt;
        ///    &lt;PointToPointMode&gt;Chapters&lt;/PointToPointMode&gt;
        ///    &lt;StartPoint&gt;1&lt;/StartPoint&gt;
        ///    &lt;EndPoint&gt;1&lt;/EndPoint&gt;
        ///    &lt;Destination&gt;{$destination}&lt;/Destination&gt;
        ///    &lt;OutputFormat&gt;Mp4&lt;/OutputFormat&gt;
        ///    &lt;OptimizeMP4&gt;true&lt;/OptimizeMP4&gt;
        ///    &lt;IPod5GSupport&gt;false&lt;/IPod5GSupport&gt;
        ///    &lt;Width&gt;{$width}&lt;/Width&gt;
        ///    &lt;Height&gt;{$height}&lt;/Height [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string queuetask {
            get {
                return ResourceManager.GetString("queuetask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerAction_16x {
            get {
                object obj = ResourceManager.GetObject("TriggerAction_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
